# Generated by Django 4.2.2 on 2023-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_favoritebook_book_favoritebook_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='lorem jskauhi ugqywgq vhvahg svcaytsf', upload_to='covers/', verbose_name='Book cover'),
        ),
    ]
